name: ci

on:
  push:
    branches:
      [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout head
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Test with unittest
        run: |
          python -m unittest